# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 21:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170716_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,11}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)]),
        ),
    ]
