# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170716_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='enrollment_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
